export const DEFAULT_PAGE = 1
export const DEFAULT_PER_PAGE = 50
export const DEFAULT_ROWS_PER_PAGE_OPTIONS = [10, 20, 50, 100]

export const DEFAULT_PAGINATION = {
	PAGE: DEFAULT_PAGE,
	PER_PAGE: DEFAULT_PER_PAGE,
	ROWS_PER_PAGE_OPTIONS: DEFAULT_ROWS_PER_PAGE_OPTIONS,
} as const
