export const CITY_OPTIONS = [
  { value: 'Jakarta Pusat', label: 'Jakarta Pusat' },
  { value: 'Jakarta Utara', label: 'Jakarta Utara' },
  { value: 'Jakarta Barat', label: 'Jakarta Barat' },
  { value: 'Jakarta Selatan', label: 'Jakarta Selatan' },
  { value: 'Jakarta Timur', label: 'Jakarta Timur' },
  { value: 'Banten - Serang', label: 'Banten - Serang' },
  { value: 'Banten - Cilegon', label: 'Banten - Cilegon' },
  { value: 'Banten - Tangerang', label: 'Banten - Tangerang' },
  { value: 'Banten - Tangerang Selatan', label: 'Banten - Tangerang Selatan' },
  { value: 'Banten - Lebak', label: 'Banten - Lebak' },
  { value: 'Banten - Pandeglang', label: 'Banten - Pandeglang' },
  { value: 'Jawa Barat - Bandung', label: 'Jawa Barat - Bandung' },
  { value: 'Jawa Barat - Bogor', label: 'Jawa Barat - Bogor' },
  { value: 'Jawa Barat - Depok', label: 'Jawa Barat - Depok' },
  { value: 'Jawa Barat - Sukabumi', label: 'Jawa Barat - Sukabumi' },
  { value: 'Jawa Barat - Cirebon', label: 'Jawa Barat - Cirebon' },
  { value: 'Jawa Barat - Tasikmalaya', label: 'Jawa Barat - Tasikmalaya' },
  { value: 'Jawa Barat - Bekasi', label: 'Jawa Barat - Bekasi' },
  { value: 'Jawa Barat - Garut', label: 'Jawa Barat - Garut' },
  { value: 'Jawa Tengah - Semarang', label: 'Jawa Tengah - Semarang' },
  {
    value: 'Jawa Tengah - Surakarta (Solo)',
    label: 'Jawa Tengah - Surakarta (Solo)',
  },
  { value: 'Jawa Tengah - Salatiga', label: 'Jawa Tengah - Salatiga' },
  { value: 'Jawa Tengah - Pekalongan', label: 'Jawa Tengah - Pekalongan' },
  { value: 'Jawa Tengah - Tegal', label: 'Jawa Tengah - Tegal' },
  { value: 'Jawa Tengah - Magelang', label: 'Jawa Tengah - Magelang' },
  { value: 'Jawa Tengah - Purwokerto', label: 'Jawa Tengah - Purwokerto' },
  { value: 'Jawa Tengah - Kudus', label: 'Jawa Tengah - Kudus' },
  { value: 'Jawa Tengah - Jepara', label: 'Jawa Tengah - Jepara' },
  { value: 'Jawa Tengah - Wonosobo', label: 'Jawa Tengah - Wonosobo' },
  { value: 'DI Yogyakarta - Yogyakarta', label: 'DI Yogyakarta - Yogyakarta' },
  { value: 'Jawa Timur - Surabaya', label: 'Jawa Timur - Surabaya' },
  { value: 'Jawa Timur - Malang', label: 'Jawa Timur - Malang' },
  { value: 'Jawa Timur - Kediri', label: 'Jawa Timur - Kediri' },
  { value: 'Jawa Timur - Probolinggo', label: 'Jawa Timur - Probolinggo' },
  { value: 'Jawa Timur - Mojokerto', label: 'Jawa Timur - Mojokerto' },
  { value: 'Jawa Timur - Sidoarjo', label: 'Jawa Timur - Sidoarjo' },
  { value: 'Jawa Timur - Blitar', label: 'Jawa Timur - Blitar' },
  { value: 'Jawa Timur - Madiun', label: 'Jawa Timur - Madiun' },
  { value: 'Jawa Timur - Pasuruan', label: 'Jawa Timur - Pasuruan' },
  { value: 'Jawa Timur - Banyuwangi', label: 'Jawa Timur - Banyuwangi' },
  { value: 'Bali - Denpasar', label: 'Bali - Denpasar' },
  { value: 'Bali - Singaraja', label: 'Bali - Singaraja' },
  { value: 'Bali - Gianyar', label: 'Bali - Gianyar' },
  { value: 'Bali - Badung', label: 'Bali - Badung' },
  { value: 'Bali - Tabanan', label: 'Bali - Tabanan' },
  {
    value: 'Nusa Tenggara Barat - Mataram',
    label: 'Nusa Tenggara Barat - Mataram',
  },
  { value: 'Nusa Tenggara Barat - Bima', label: 'Nusa Tenggara Barat - Bima' },
  {
    value: 'Nusa Tenggara Barat - Sumbawa',
    label: 'Nusa Tenggara Barat - Sumbawa',
  },
  {
    value: 'Nusa Tenggara Barat - Dompu',
    label: 'Nusa Tenggara Barat - Dompu',
  },
  {
    value: 'Nusa Tenggara Timur - Kupang',
    label: 'Nusa Tenggara Timur - Kupang',
  },
  {
    value: 'Nusa Tenggara Timur - Maumere',
    label: 'Nusa Tenggara Timur - Maumere',
  },
  { value: 'Nusa Tenggara Timur - Ende', label: 'Nusa Tenggara Timur - Ende' },
  {
    value: 'Nusa Tenggara Timur - Ruteng',
    label: 'Nusa Tenggara Timur - Ruteng',
  },
  { value: 'Aceh - Banda Aceh', label: 'Aceh - Banda Aceh' },
  { value: 'Aceh - Sabang', label: 'Aceh - Sabang' },
  { value: 'Aceh - Langsa', label: 'Aceh - Langsa' },
  { value: 'Aceh - Lhokseumawe', label: 'Aceh - Lhokseumawe' },
  { value: 'Aceh - Meulaboh', label: 'Aceh - Meulaboh' },
  { value: 'Sumatera Utara - Medan', label: 'Sumatera Utara - Medan' },
  { value: 'Sumatera Utara - Binjai', label: 'Sumatera Utara - Binjai' },
  {
    value: 'Sumatera Utara - Pematang Siantar',
    label: 'Sumatera Utara - Pematang Siantar',
  },
  {
    value: 'Sumatera Utara - Tebing Tinggi',
    label: 'Sumatera Utara - Tebing Tinggi',
  },
  { value: 'Sumatera Utara - Sibolga', label: 'Sumatera Utara - Sibolga' },
  {
    value: 'Sumatera Utara - Padang Sidempuan',
    label: 'Sumatera Utara - Padang Sidempuan',
  },
  {
    value: 'Sumatera Utara - Tanjung Balai',
    label: 'Sumatera Utara - Tanjung Balai',
  },
  {
    value: 'Sumatera Utara - Rantau Prapat',
    label: 'Sumatera Utara - Rantau Prapat',
  },
  { value: 'Sumatera Barat - Padang', label: 'Sumatera Barat - Padang' },
  {
    value: 'Sumatera Barat - Bukittinggi',
    label: 'Sumatera Barat - Bukittinggi',
  },
  {
    value: 'Sumatera Barat - Payakumbuh',
    label: 'Sumatera Barat - Payakumbuh',
  },
  { value: 'Sumatera Barat - Solok', label: 'Sumatera Barat - Solok' },
  { value: 'Sumatera Barat - Pariaman', label: 'Sumatera Barat - Pariaman' },
  {
    value: 'Sumatera Barat - Padang Panjang',
    label: 'Sumatera Barat - Padang Panjang',
  },
  {
    value: 'Sumatera Barat - Sawahlunto',
    label: 'Sumatera Barat - Sawahlunto',
  },
  {
    value: 'Sumatera Selatan - Palembang',
    label: 'Sumatera Selatan - Palembang',
  },
  {
    value: 'Sumatera Selatan - Lubuklinggau',
    label: 'Sumatera Selatan - Lubuklinggau',
  },
  {
    value: 'Sumatera Selatan - Prabumulih',
    label: 'Sumatera Selatan - Prabumulih',
  },
  {
    value: 'Sumatera Selatan - Pagar Alam',
    label: 'Sumatera Selatan - Pagar Alam',
  },
  { value: 'Sumatera Selatan - Lahat', label: 'Sumatera Selatan - Lahat' },
  {
    value: 'Sumatera Selatan - Muara Enim',
    label: 'Sumatera Selatan - Muara Enim',
  },
  { value: 'Riau - Pekanbaru', label: 'Riau - Pekanbaru' },
  { value: 'Riau - Dumai', label: 'Riau - Dumai' },
  { value: 'Riau - Rengat', label: 'Riau - Rengat' },
  { value: 'Riau - Bangkinang', label: 'Riau - Bangkinang' },
  { value: 'Kepulauan Riau - Batam', label: 'Kepulauan Riau - Batam' },
  {
    value: 'Kepulauan Riau - Tanjung Pinang',
    label: 'Kepulauan Riau - Tanjung Pinang',
  },
  { value: 'Kepulauan Riau - Karimun', label: 'Kepulauan Riau - Karimun' },
  { value: 'Kepulauan Riau - Bintan', label: 'Kepulauan Riau - Bintan' },
  { value: 'Kepulauan Riau - Natuna', label: 'Kepulauan Riau - Natuna' },
  { value: 'Jambi - Jambi', label: 'Jambi - Jambi' },
  { value: 'Jambi - Sungaipenuh', label: 'Jambi - Sungaipenuh' },
  { value: 'Jambi - Muaro Bungo', label: 'Jambi - Muaro Bungo' },
  { value: 'Jambi - Sarolangun', label: 'Jambi - Sarolangun' },
  { value: 'Jambi - Kerinci', label: 'Jambi - Kerinci' },
  { value: 'Bengkulu - Bandar Lampung', label: 'Bengkulu - Bandar Lampung' },
  { value: 'Bengkulu - Metro', label: 'Bengkulu - Metro' },
  { value: 'Bengkulu - Lampung Selatan', label: 'Bengkulu - Lampung Selatan' },
  { value: 'Bengkulu - Pringsewu', label: 'Bengkulu - Pringsewu' },
  { value: 'Kalimantan Barat - Sekadau', label: 'Kalimantan Barat - Sekadau' },
  {
    value: 'Kalimantan Barat - Pontianak',
    label: 'Kalimantan Barat - Pontianak',
  },
  {
    value: 'Kalimantan Barat - Singkawang',
    label: 'Kalimantan Barat - Singkawang',
  },
  { value: 'Kalimantan Barat - Sambas', label: 'Kalimantan Barat - Sambas' },
  { value: 'Kalimantan Barat - Sintang', label: 'Kalimantan Barat - Sintang' },
  {
    value: 'Kalimantan Barat - Ketapang',
    label: 'Kalimantan Barat - Ketapang',
  },
  {
    value: 'Kalimantan Tengah - Palangka Raya',
    label: 'Kalimantan Tengah - Palangka Raya',
  },
  { value: 'Kalimantan Tengah - Sampit', label: 'Kalimantan Tengah - Sampit' },
  {
    value: 'Kalimantan Tengah - Pangkalan Bun',
    label: 'Kalimantan Tengah - Pangkalan Bun',
  },
  {
    value: 'Kalimantan Tengah - Katingan',
    label: 'Kalimantan Tengah - Katingan',
  },
  {
    value: 'Kalimantan Selatan - Samarinda',
    label: 'Kalimantan Selatan - Samarinda',
  },
  {
    value: 'Kalimantan Selatan - Balikpapan',
    label: 'Kalimantan Selatan - Balikpapan',
  },
  {
    value: 'Kalimantan Selatan - Bontang',
    label: 'Kalimantan Selatan - Bontang',
  },
  {
    value: 'Kalimantan Selatan - Tenggarong',
    label: 'Kalimantan Selatan - Tenggarong',
  },
  {
    value: 'Kalimantan Selatan - Kutai Kartanegara',
    label: 'Kalimantan Selatan - Kutai Kartanegara',
  },
  { value: 'Kalimantan Utara - Tarakan', label: 'Kalimantan Utara - Tarakan' },
  { value: 'Kalimantan Utara - Nunukan', label: 'Kalimantan Utara - Nunukan' },
  { value: 'Kalimantan Utara - Malinau', label: 'Kalimantan Utara - Malinau' },
  {
    value: 'Kalimantan Utara - Tana Tidung',
    label: 'Kalimantan Utara - Tana Tidung',
  },
  { value: 'Sulawesi Utara - Manado', label: 'Sulawesi Utara - Manado' },
  { value: 'Sulawesi Utara - Bitung', label: 'Sulawesi Utara - Bitung' },
  { value: 'Sulawesi Utara - Tomohon', label: 'Sulawesi Utara - Tomohon' },
  {
    value: 'Sulawesi Utara - Kotamobagu',
    label: 'Sulawesi Utara - Kotamobagu',
  },
  { value: 'Sulawesi Tengah - Palu', label: 'Sulawesi Tengah - Palu' },
  { value: 'Sulawesi Tengah - Poso', label: 'Sulawesi Tengah - Poso' },
  { value: 'Sulawesi Tengah - Donggala', label: 'Sulawesi Tengah - Donggala' },
  { value: 'Sulawesi Tengah - Morowali', label: 'Sulawesi Tengah - Morowali' },
  {
    value: 'Sulawesi Selatan - Makassar',
    label: 'Sulawesi Selatan - Makassar',
  },
  {
    value: 'Sulawesi Selatan - Parepare',
    label: 'Sulawesi Selatan - Parepare',
  },
  { value: 'Sulawesi Selatan - Palopo', label: 'Sulawesi Selatan - Palopo' },
  {
    value: 'Sulawesi Selatan - Enrekang',
    label: 'Sulawesi Selatan - Enrekang',
  },
  { value: 'Sulawesi Selatan - Takalar', label: 'Sulawesi Selatan - Takalar' },
  {
    value: 'Sulawesi Tenggara - Kendari',
    label: 'Sulawesi Tenggara - Kendari',
  },
  { value: 'Sulawesi Tenggara - Baubau', label: 'Sulawesi Tenggara - Baubau' },
  { value: 'Sulawesi Tenggara - Buton', label: 'Sulawesi Tenggara - Buton' },
  { value: 'Sulawesi Tenggara - Kolaka', label: 'Sulawesi Tenggara - Kolaka' },
  { value: 'Gorontalo', label: 'Gorontalo' },
  { value: 'Sulawesi Barat - Mamuju', label: 'Sulawesi Barat - Mamuju' },
  {
    value: 'Sulawesi Barat - Polewali Mandar',
    label: 'Sulawesi Barat - Polewali Mandar',
  },
  { value: 'Maluku - Ambon', label: 'Maluku - Ambon' },
  { value: 'Maluku - Tual', label: 'Maluku - Tual' },
  { value: 'Maluku - Maluku Tenggara', label: 'Maluku - Maluku Tenggara' },
  { value: 'Maluku Utara - Ternate', label: 'Maluku Utara - Ternate' },
  { value: 'Maluku Utara - Tidore', label: 'Maluku Utara - Tidore' },
  { value: 'Maluku Utara - Sofifi', label: 'Maluku Utara - Sofifi' },
  { value: 'Papua - Jayapura', label: 'Papua - Jayapura' },
  { value: 'Papua - Sorong', label: 'Papua - Sorong' },
  { value: 'Papua - Merauke', label: 'Papua - Merauke' },
  { value: 'Papua - Nabire', label: 'Papua - Nabire' },
  { value: 'Papua - Biak', label: 'Papua - Biak' },
  { value: 'Papua - Timika', label: 'Papua - Timika' },
  { value: 'Papua Barat - Manokwari', label: 'Papua Barat - Manokwari' },
  { value: 'Papua Barat - Sorong', label: 'Papua Barat - Sorong' },
  { value: 'Papua Barat - Fakfak', label: 'Papua Barat - Fakfak' },
]
