export enum UserRole {
	TRADE_MT5 = 'trade_mt5',
	SUPER_ADMIN = 'super_admin',
	STAFF_SALES_IDN_SFI = 'staff_sales_idn_sfi',
	STAFF_ONBOARDING_IDN_SFI = 'staff_onboarding_idn_sfi',
	STAFF_RISK_IDN_SFI = 'staff_risk_idn_sfi',
	STAFF_COMPLIANCE_IDN_SFI = 'staff_compliance_idn_sfi',
	STAFF_CEO_IDN_SFI = 'staff_ceo_idn_sfi',
	STAFF_FINANCE_IDN_SFI = 'staff_finance_idn_sfi',
	STAFF_TREASURY_IDN_SFI = 'staff_treasury_idn_sfi',
	STAFF_ETS_IDN_SFI = 'staff_ets_idn_sfi',
	STAFF_OPERATIONS_IDN_SFI = 'staff_operations_idn_sfi',
	STAFF_ONBOARDING_MAKER_IDN_SFI = 'staff_onboardingmaker_idn_sfi',
	STAFF_ONBOARDING_CHECKER_IDN_SFI = 'staff_onboardingchecker_idn_sfi',
	STAFF_SENIOR_MANAGEMENT_IDN_SFI = 'staff_senior_management_idn_sfi',
	STAFF_NEW_ACCOUNTS_IDN_SFI = 'staff_new_accounts_idn_sfi',
	MANAGER_SALES_IDN_SFI = 'manager_sales_idn_sfi',
	MANAGER_ONBOARDING_IDN_SFI = 'manager_onboarding_idn_sfi',
	MANAGER_RISK_IDN_SFI = 'manager_risk_idn_sfi',
	MANAGER_COMPLIANCE_IDN_SFI = 'manager_compliance_idn_sfi',
	MANAGER_CEO_IDN_SFI = 'manager_ceo_idn_sfi',
	MANAGER_FINANCE_IDN_SFI = 'manager_finance_idn_sfi',
	MANAGER_TREASURY_IDN_SFI = 'manager_treasury_idn_sfi',
	MANAGER_ETS_IDN_SFI = 'manager_ets_idn_sfi',
	MANAGER_OPERATIONS_IDN_SFI = 'manager_operations_idn_sfi',
	MANAGER_ONBOARDING_MAKER_IDN_SFI = 'manager_onboardingmaker_idn_sfi',
	MANAGER_ONBOARDING_CHECKER_IDN_SFI = 'manager_onboardingchecker_idn_sfi',
	MANAGER_SENIOR_MANAGEMENT_IDN_SFI = 'manager_senior_management_idn_sfi',
	MANAGER_NEW_ACCOUNTS_IDN_SFI = 'manager_new_accounts_idn_sfi',
	TRADE_DEMO = 'trade_demo',
	ADMIN_SFI = 'admin_sfi',
	TRADE_CQG = 'trade_cqg',
	CUSTOMER = 'customer',
}

export const USER_ROLES = Object.values(UserRole)
